config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :adminusers
      resources :users
      resources :outputs
      resources :books

      root to: "adminusers#index"
    end
  # devise_for :adminusers
  devise_for :adminusers, controllers: {
    sessions: 'adminusers/sessions',
    :registrations => 'adminusers/registrations',
    :passwords => 'adminusers/passwords'
  }

  resources :books, shallow: true do
    resources :outputs do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
  end

  devise_for :users
  root to:'books#root'

  get '/about', to:'static_pages#about'
  get '/profile/edit', to:'users#edit'
  post '/profile/edit', to:'users#update'
  resources :users

  # 基本情報編集後の同じ画面に戻るようにした
  as :user do
    get 'users/edit',:to =>'devise/registrations#edit',:as => :user_root
  end

  #フォロー機能
  resources :relationships, only: [:create, :destroy]

  # 通知機能
  resources :notifications, only: [:index]
  delete  '/notifications', to: 'notifications#destroy_all'

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_side, only: [:home]

  def home
    @outputs = Output.where(book_id: @thisweek.id)
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>


<section class="hero is-default is-bold mb-5 parallax-bg">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title has-text-white">今週の課題図書</h1>
      <div class="columns is-vcentered">
        <div class="column is-3 is-offset-2">
          <figure class="image is-4by4 container is-centered">
            <%= attachment_image_tag @thisweek, :book_image, fallback: "no-image", class:"" %>
          </figure>
        </div>
        <div class="column is-7">
          <h1 class="title is-2 has-text-white">
            <%= @thisweek.title %>
          </h1>
          <h2 class="subtitle is-4 has-text-white">
              <%= @thisweek.body %>
          </h2>
          <br>
          <p class="has-text-centered">
            <a class="button is-medium is-primary">
              購入する
            </a>
            <%= link_to 'アウトプットする', new_book_output_path(@thisweek) , class:"button is-medium is-danger" %>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

<main class="columns">
  <div class="submenu column is-3">
    <aside class="box menu">
      <p class="menu-label">プロフィール</p>
      <% if @user %>
        <%= link_to user_path(current_user) do %>
          <figure class="image is-128x128">
            <%= attachment_image_tag @user, :profile_image, fallback: "no-image",class:"is-rounded" %>
          </figure>
        <% end %>
        <p class="menu-label">ニックネーム</p>
        <%= link_to user_path(current_user) do %>
        <p class="is-size-5 has-text-dark"><%= @user.username %></p>
        <% end %>
        <p class="menu-label">フォロー</p>
        <p class="menu-label">フォロワー</p>
        <p class="menu-label">読んだ本の数</p>
        <p class="menu-label">集めたいいねの数</p>
      <% else %>
        <figure class="image is-128x128">
          <%= attachment_image_tag @user, :profile_image, fallback: "no-image",class:"is-rounded" %>
        </figure>
        <p class="menu-label">ニックネーム</p>
        <p class="is-size-5 has-text-dark">ゲストユーザー</p>
      <% end %>
    </aside>
    <aside class="box menu">
      <p class="menu-label">来週の課題図書</p>
      <div class="box">
        <figure class="image is-4by4 container is-centered">
          <%= attachment_image_tag @nextweek, :book_image, fallback: "no-image", class:"" %>
        </figure>
      </div>
      <p class="menu-label">タイトル</p>
      <div class="is-size-5 title"><%= @nextweek.title %></div>
      <p class="menu-label">説明</p>
      <div><%= @nextweek.body %></div>
   </aside>
  </div>

  <div class="column is-9">
    <div class="hero is-bold">
      <div class="hero-body level">
        <div class="is-size-4 has-text-weight-bold has-text-white">みんなのアウトプット</div>
        <div class="level-item level-right">
          <div class="field has-addons">
            <div class="control">
              <input class="input" type="text" name="search" placeholder="キーワード検索">
            </div>
            <div class="control">
              <a class="button is-info"><i class="fa fa-search"></i>検索</a>
            </div>              
          </div>
        </div>
      </div>
    </div>
    <section class="level">
      <div class="level-left">
        <div class="level-item tabs">
          <ul>
            <li class="is-active"><a class="has-text-white">全ての投稿</a></li>
            <li><a class="has-text-white">フォローした人の投稿</a></li>
            <li><a class="has-text-white">フォローした人がいいねした投稿</a></li>
          </ul>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item tabs">
          <ul>
            <li class="is-active"><a class="has-text-white">新しい順</a></li>
            <li><a class="has-text-white">古い順</a></li>
            <li><a class="has-text-white">いいねが多い順</a></li>
          </ul>
        </div>
      </div>
    </section>

    <% @outputs.each do |output| %>
    <% output_user = User.find(output.user_id) %>
      <article class="box media">
        <figure class="media-left">
          <%= link_to user_path(output_user) do %>
            <figure class="image is-64x64">
              <%= attachment_image_tag output_user, :profile_image, fallback: "no-image",class:"is-rounded" %>
            </figure>
          <% end %>
        </figure>
        <div class="media-content">
          <div class="content">
            <p><strong><%= output_user.username %></strong><br>
              <%= output.body %><br>
              <small><a>Like</a> · <a>Reply</a> · 3 hrs</small>
            </p>
          </div>
          <article class="media">
            <figure class="media-left">
              <p class="image is-48x48">
                <img src="http://placehold.it/96x96" class="is-rounded">
              </p>
            </figure>
            <div class="media-content">
              <div class="content">
                <p><strong>Sean Brown</strong><br>
                  コメントコメントコメントコメントコメントコメントコメントコメントコメントコメント<br>
                  <small><a>Like</a> · <a>Reply</a> · 2 hrs</small>
                </p>
              </div>
            </div>
          </article>
        </div>
      </article>
    <% end %>

  </div>
</main>