config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :adminusers
      resources :users
      resources :outputs
      resources :books

      root to: "adminusers#index"
    end
  # devise_for :adminusers
  devise_for :adminusers, controllers: {
    sessions: 'adminusers/sessions',
    :registrations => 'adminusers/registrations',
    :passwords => 'adminusers/passwords'
  }

  resources :books, shallow: true do
    resources :outputs do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
  end

  devise_for :users
  root to:'books#root'

  get '/about', to:'static_pages#about'
  get '/profile/edit', to:'users#edit'
  post '/profile/edit', to:'users#update'
  resources :users

  # 基本情報編集後の同じ画面に戻るようにした
  as :user do
    get 'users/edit',:to =>'devise/registrations#edit',:as => :user_root
  end

  #フォロー機能
  resources :relationships, only: [:create, :destroy]

  # 通知機能
  resources :notifications, only: [:index]
  delete  '/notifications', to: 'notifications#destroy_all'

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable, :timeoutable

  #refileで画像を使う設定
  attachment :profile_image

  #投稿機能
  has_many :outputs, dependent: :destroy

  #いいね機能
  has_many :favorites, dependent: :destroy

  def already_favorited?(output)
    self.favorites.exists?(output_id: output.id)
  end

  #フォロー機能
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  #コメント機能
  has_many :comments

  # scope :already_favorited?, -> query {
  #   self.favorites.exists?(output_id: query.id)
  # }

  # 通知機能
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

   #フォロー時の通知
  def create_notification_follow!(current_user)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    def resource_params
      params.require(:user).permit(:username,:profile,:profile_image,:twitter,:instagram,:facebook,:website,:output_ids, :email, :password, :password_confirmation)
    end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    #http://blog.319ring.net/2016/05/14/custom_view_administrate/ このページでは、strong parametersを下のように設定していたが、うまく動作しなかったので、上のようにパスワードをpermitしたが、脆弱性が心配
    # def permitted_attributes
      # dashboard.permitted_attributes << %w(password password_confirmation)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update , :index]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @users = User.all
    @books = Book.get_user_books({user_id: @user.id})
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(current_user), notice: 'プロフィールが更新されました。' }
      else
        format.html { render :edit }
      end
    end
  end

  private
  def set_user
    @user = User.find(current_user.id)
  end
  def user_params
    params.require(:user).permit(:username,:profile,:profile_image,:twitter,:instagram,:facebook,:website)
  end
  def correct_user
    redirect_to(root_url) unless @user == current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "プロフィールの編集") %>

<section class="hero is-fullheight-with-navbar has-text-white">
  <div class="hero-body has-text-centered">
    <div class="setup">
      <div class="is-size-3 my-5">プロフィール編集</div>
      <%= form_with model: @user, url: profile_edit_path, local:true, method: :post do |form| %>
        <div class="field">
          <div class="control">
            <%= form.label :username, "ニックネーム"%>
            <span class="has-text-danger">*</span>
            <%= form.text_field :username, class: "input is-medium is-rounded textbox", placeholder: @user.username, required: true %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= form.label :profile_image, "プロフィール画像"%>
            <%= form.attachment_field :profile_image, class: "input is-light textbox is-rounded",placeholder: @user.profile_image %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= form.label :profile, "プロフィール"%>
            <%= form.text_area :profile, class: "input is-medium textbox textarea textboxcss", placeholder: @user.profile %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= form.label :twitter, "Twitter URL"%>
            <%= form.text_field :twitter, class: "input is-medium is-rounded textbox", placeholder: @user.twitter %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= form.label :instagram, "Instagram URL"%>
            <%= form.text_field :instagram, class: "input is-medium is-rounded textbox", placeholder: @user.instagram %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= form.label :facebook, "Facebook URL"%>
            <%= form.text_field :facebook, class: "input is-medium is-rounded textbox", placeholder: @user.facebook %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= form.label :website, "WebサイトURL"%>
            <%= form.text_field :website, class: "input is-medium is-rounded textbox", placeholder: @user.website %>
          </div>
        </div>
        <br/>
        <%= form.submit "プロフィール更新", class: "button is-primary is-block is-fullwidth is-medium is-rounded" %>
      <% end %>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>

<div class="hero is-info is-bold">
   <div class="hero-body">
       <div class="container">
          <h1 class="title">ユーザー一覧</h1>

          <div class="container">
            現在のユーザー：<%= current_user.email %>
          </div>

       </div>
   </div>
</div>

  <section class="section">
    <div class="container">
      <div class="columns is-multiline">
        <% @users.each do |user| %>
          <div class="column is-3">
            <div class="card">
              <div class="card-content">
                <div class="card-image">
                  <figure class="image">
                    <%= link_to user_path(user) do %>
                      <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                    <% end %>
                  </figure>
                </div>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <div class="title"><%=link_to user.username, user_path(user) %></div>
                  </div>
                </div>
                <div class="content">
                  user.id:<%= user.id %><br/>
                  user.email:<%= user.email %><br/>
                  user.username:<%= user.username %><br/>
                  user.user.profile<%= user.profile %><br/>
                  <%= user.twitter %><br/>
                  <%= user.instagram %><br/>
                  <%= user.facebook %><br/>
                  <%= user.website %><br/>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>

app/views/users/show.html.erb
<% if user_signed_in? && @user.id == current_user.id %>
  <% provide(:title, "マイページ") %>
<% else %>
  <% provide(:title, "#{@user.username}") %>
<% end %>

<section class="hero is-default is-bold mb-5 parallax-bg">
  <div class="hero-body">
    <div class="container ">
      <div class="columns is-vcentered">
        <div class="column is-3 is-offset-2">
          <figure class="image is-4by4 container is-centered">
            <%= attachment_image_tag @user, :profile_image, fallback: "no-image", class:"is-rounded" %>
          </figure>
        </div>
        <div class="column is-6 is-offset-1">
          <p class="has-text-right">
            <% if user_signed_in? %>
            <%= render 'relationships/follow_button', user: @user %>
            <% end %>
            <% if user_signed_in? && @user.id == current_user.id %>
              <%= link_to 'プロフィール編集', profile_edit_path ,method: :get, class:"button is-medium is-light" %>
            <% end %>
          </p>
          <h1 class="title is-2 has-text-white">
            <%= @user.username %>
          </h1>
          <h2 class="subtitle is-4 has-text-white">
            <%= @user.profile %>
          </h2>
          <% if @user.twitter?%>
            <%= link_to 'Twitter', @user.twitter ,method: :get, class:"button is-medium is-light" %>
          <% end %>
          <% if @user.instagram?%>
            <%= link_to 'Instagram', @user.instagram ,method: :get, class:"button is-medium is-light" %>
          <% end %>
          <% if @user.facebook?%>
            <%= link_to 'Facebook', @user.facebook ,method: :get, class:"button is-medium is-light" %>
          <% end %>
          <% if @user.website?%>
            <%= link_to 'WEBサイト', @user.website ,method: :get, class:"button is-medium is-light" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="hero is-bold">
  <div class="hero-body level">
    <div class="is-size-4 has-text-weight-bold has-text-white title">これまでのアウトプット</div>
    <%#<div class="level-item level-right">
      <div class="field has-addons">
        <div class="control">
            <input class="input" type="text" name="search" placeholder="キーワード検索">
        </div>
        <div class="control">
            <a class="button is-info"><i class="fa fa-search"></i>検索</a>
        </div>
      </div>
    </div>%>
  </div>
</div>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @books.each do |book| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to book_path(book) do %>
                    <%= attachment_image_tag book, :book_image, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to book.title, book_path(book) %></div>
                </div>
              </div>
              <div class="content">
                book.id：<%= book.id %><br/>
                説明：<%= book.body %><br/>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>