config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :adminusers
      resources :users
      resources :outputs
      resources :books

      root to: "adminusers#index"
    end
  # devise_for :adminusers
  devise_for :adminusers, controllers: {
    sessions: 'adminusers/sessions',
    :registrations => 'adminusers/registrations',
    :passwords => 'adminusers/passwords'
  }

  resources :books, shallow: true do
    resources :outputs do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
  end

  devise_for :users
  root to:'books#root'

  get '/about', to:'static_pages#about'
  get '/profile/edit', to:'users#edit'
  post '/profile/edit', to:'users#update'
  resources :users

  # 基本情報編集後の同じ画面に戻るようにした
  as :user do
    get 'users/edit',:to =>'devise/registrations#edit',:as => :user_root
  end

  #フォロー機能
  resources :relationships, only: [:create, :destroy]

  # 通知機能
  resources :notifications, only: [:index]
  delete  '/notifications', to: 'notifications#destroy_all'

  
end

app/models/output.rb
class Output < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates_uniqueness_of :book_id, scope: :user_id

  scope :search_outputs, -> query {
    s = select("outputs.*")
    if query[:keyword].present?
      s = s.where('LOWER(outputs.body) LIKE LOWER(?)', "%#{query[:keyword]}%")
    end
    if query[:sort_order].blank? || query[:sort_order] == "0"
      s = s.ordered_desc
    elsif query[:sort_order] == "1"
      s = s.ordered_asc
    end

    if query[:narrow_down] == "1"
      s = s.left_joins(:user).joins('LEFT OUTER JOIN "relationships" ON "relationships"."follow_id" = "outputs"."user_id"')
      if query[:current_user_id].present?
        s = s.where(relationships:{user_id: query[:current_user_id]})
      end
    elsif query[:narrow_down] == "2"
      s = s.left_joins(:user).joins('LEFT OUTER JOIN "favorites" ON "favorites"."output_id" = "outputs"."id"').joins('LEFT OUTER JOIN "relationships" ON "relationships"."follow_id" = "favorites"."user_id"')
      if query[:current_user_id].present?
        s = s.where(relationships:{user_id: query[:current_user_id]})
      end
    end
    s
  }

  scope :ordered_asc, -> { order(created_at: :asc) }
  scope :ordered_desc, -> { order(created_at: :desc) }


  # 通知機能
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      output_id: id,
      visited_id: user_id,
      action: "like"
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
      # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
      temp_ids = Comment.select(:user_id).where(output_id: id).where.not(user_id: current_user.id).distinct
      temp_ids.each do |temp_id|
          save_notification_comment!(current_user, comment_id, temp_id['user_id'])
      end
      # まだ誰もコメントしていない場合は、投稿者に通知を送る
      save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
      # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
      notification = current_user.active_notifications.new(
        output_id: id,
        comment_id: comment_id,
        visited_id: visited_id,
        action: 'comment'
      )
      # 自分の投稿に対するコメントの場合は、通知済みとする
      if notification.visiter_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end
  

end

app/controllers/admin/outputs_controller.rb
module Admin
  class OutputsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_output, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_book, only: [:new, :create]
  before_action :set_side

  # GET /outputs/1
  # GET /outputs/1.json
  def show
    @output_user = User.find(@output.user_id)
    @comments = @output.comments
    @comment = Comment.new
  end

  # GET /outputs/new
  def new
    @output = Output.new
  end

  # GET /outputs/1/edit
  def edit
  end

  # POST /outputs
  # POST /outputs.json
  def create
    @output = @book.outputs.build(output_params)
    @output.user_id = current_user.id
    respond_to do |format|
      if @output.save
        format.html { redirect_to @book, notice: 'アウトプットを投稿しました。' }
        format.json { render :show, status: :created, location: @book }
      else
        @output.errors.messages.delete(:book_id)
        @output.errors.add("投稿","がすでに存在しています。")
        format.html { render :new }
        format.json { render json: @output.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outputs/1
  # PATCH/PUT /outputs/1.json
  def update
    respond_to do |format|
      if @output.update(output_params)
        format.html { redirect_to output_path(@output.id), notice: 'アウトプットが更新されました。' }
        format.json { render :show, status: :ok, location: @output }
      else
        format.html { render :edit }
        format.json { render json: @output.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outputs/1
  # DELETE /outputs/1.json
  def destroy
    @output.destroy
    respond_to do |format|
      format.html { redirect_to book_path(@output.book_id), notice: 'アウトプットが削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_output
      @output = Output.find_by(id:params[:id])
      # @output = Output.find(params[:id])
    end
    def set_book
      @book = Book.find(params[:book_id])
    end
    # Only allow a list of trusted parameters through.
    def output_params
      # params.fetch(:output, {})
      params.require(:output).permit(:body)
    end
    def correct_user
      redirect_to(root_url) unless @output.user == current_user
    end
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/views/outputs/_form.html.erb
<%#= form_with(model: @output, local: true) do |form| %>
<%#= form_with(model: @output, url: (@output.new_record? ? book_outputs_path(@book, @output) : book_output_path(@output)), local: true) do |form| %>

<section class="hero is-fullheight-with-navbar">
  <div class="hero-body has-text-centered">
    <div class="setup">
      <%= form_with(model: @output, url: (@output.new_record? ? book_outputs_path(@book, @output) : output_path(@output)), local: true) do |form| %>

        <div class="field">
          <div class="control">
            <%= form.label :body, "アウトプットを投稿する",class:"is-size-3 my-5 has-text-white is-inline"%>
            <span class="has-text-danger">*</span>
            <%= form.text_area :body, class: "input is-medium textbox textarea textboxcss my-5", required: true %>
          </div>
        </div>

        <div class="actions">
          <%= form.submit "投稿する",class:"button is-primary is-block is-fullwidth is-medium is-rounded" %>
        </div>
      <% end %>

    </div>
  </div>
</section>

app/views/outputs/edit.html.erb
<% provide(:title, "アウトプットの編集") %>

<%= render 'form', output: @output %>

app/views/outputs/new.html.erb
<% provide(:title, "アウトプット投稿") %>

  <%= render 'form', output: @output %>

app/views/outputs/show.html.erb
<% provide(:title, "投稿詳細") %>

<section class="hero is-default is-bold mb-5 parallax-bg">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title has-text-white">投稿詳細</h1>
    </div>
  </div>
</section>

<main class="columns">
  <div class="submenu column is-3">
    <aside class="box menu">
      <p class="menu-label">プロフィール</p>
        <%= link_to user_path(@output_user) do %>
          <figure class="image is-128x128">
            <%= attachment_image_tag @output_user, :profile_image, fallback: "no-image",class:"is-rounded" %>
          </figure>
        <% end %>
        <p class="menu-label">ニックネーム</p>
        <%= link_to user_path(@output_user) do %>
        <p class="is-size-5 has-text-dark"><%= @output_user.username %></p>
        <% end %>

        <p class="menu-label">フォロー</p>
          <%= @output_user.followings.count%>
        <p class="menu-label">フォロワー</p>
          <%= @output_user.followers.count%>
        <p class="menu-label">読んだ本の数</p>
          <%= Output.where(user_id: @output_user.id).count %>
        <p class="menu-label">集めたいいねの数</p>
          <% user_outputs = Output.where(user_id: @output_user.id)
            n = 0
            user_outputs.each do |output|
              n = n + output.favorites.count
            end
          %>
          <%= n %>

          <% if user_signed_in? %>
            <%= render 'relationships/follow_button', user: @output_user %>
          <% end %>

    </aside>
  </div>

  <div class="column is-9">

    <article class="box media">
      <figure class="media-left">
        <%= link_to user_path(@output_user) do %>
          <figure class="image is-64x64">
            <%= attachment_image_tag @output_user, :profile_image, fallback: "no-image",class:"is-rounded" %>
          </figure>
        <% end %>
      </figure>
      <div class="media-content">
        <div class="content">
          <p><strong><%= @output_user.username %></strong><br>
            <%= @output.body %><br>
            <%= @output.created_at.strftime("%Y-%m-%d %H:%M") %><br>
            <small>
            <% if user_signed_in? && current_user.already_favorited?(@output) %>
              <% favorite = Favorite.find_by(user_id:current_user.id, output_id: output.id) %>
              <%= link_to favorite_path(favorite,output),method: :delete do %>
                <i class="fas fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to output_favorites_path(@output),method: :post  do %>
                <i class="far fa-heart"></i>
              <% end %>
            <% end %>
            <%= @output.favorites.count %><br>

            <% if current_user == @output_user%>
            <%= link_to '投稿の編集', edit_output_path(@output) %> · <%= link_to '投稿の削除', output_path(output.id), method: :delete, data: { confirm: '元に戻せませんが、削除してもいいですか？' } %>
            <% end %>
            </small>
          </p>
        </div>
      </div>
    </article>

    <h1 class="has-text-white mt-4 mb-4 title">コメント一覧</h1>

    <% @comments.each do |c| %>
      <% comment_user = User.find_by(id: c.user_id)%>
      <article class="media has-text-white">
        <figure class="media-left">
          <figure class="image is-48x48">
            <%= attachment_image_tag comment_user, :profile_image, fallback: "no-image",class:"is-rounded" %>
          </figure>
        </figure>
        <div class="media-content">
          <div class="content">
            <p class="has-text-white"><strong class="has-text-white"><%= comment_user.username %></strong><br>
              <%= c.body %><br>
            </p>
          </div>
        </div>
      </article>
    <% end %>
    

    <%= form_with model: @comment, url: output_comments_path(@output), local: true, method: :post do |form| %>

      <div class="field">
        <div class="control">
          <%= form.text_area :body, class: "input is-medium textbox textarea textboxcss my-5", required: true %>
          <%= form.hidden_field :output_id, value: @output.id %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit "コメントする",class:"button is-primary is-block is-fullwidth is-medium is-rounded" %>
      </div>
    <% end %>
  </div>
</main>