config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :adminusers
      resources :users
      resources :outputs
      resources :books

      root to: "adminusers#index"
    end
  # devise_for :adminusers
  devise_for :adminusers, controllers: {
    sessions: 'adminusers/sessions',
    :registrations => 'adminusers/registrations',
    :passwords => 'adminusers/passwords'
  }

  resources :books, shallow: true do
    resources :outputs do
      resources :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
    end
  end

  devise_for :users
  root to:'books#root'

  get '/about', to:'static_pages#about'
  get '/profile/edit', to:'users#edit'
  post '/profile/edit', to:'users#update'
  resources :users

  # 基本情報編集後の同じ画面に戻るようにした
  as :user do
    get 'users/edit',:to =>'devise/registrations#edit',:as => :user_root
  end

  #フォロー機能
  resources :relationships, only: [:create, :destroy]

  # 通知機能
  resources :notifications, only: [:index]
  delete  '/notifications', to: 'notifications#destroy_all'

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | 読書習慣</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600&display=swap" rel="stylesheet">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- jquery cdn -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- font awesome cdn -->
    <link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet">
    
  </head>

  <body>

  <% if flash[:notice] %>
    <div class="notification is-primary">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="notification is-danger">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  <% if resource.present? %>
    <%= render "devise/shared/error_messages", resource: resource %>
  <% end %>
  <% if output.errors.any? %>
    <% output.errors.full_messages.each do |message| %>
      <div class="notification is-danger">
        <p class="alert"><%= message %></p>
      </div>
    <% end %>
  <% end %>

  

  <nav class="navbar is-dark">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-4 has-text-white">読書習慣</h1>
      <% end %>
      <% if adminuser_signed_in? %>
        <li class="navbar-item">
          <%= link_to '管理者ログアウト',destroy_adminuser_session_path, method: :delete, class:"button is-warning" %>
        </li>
        <li class="navbar-item">
          <%= link_to '管理者画面へ',admin_root_path, method: :get, class:"button is-primary" %>
        </li>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <% if user_signed_in? %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end">
          <%= link_to '今週の課題図書', root_url , class:"navbar-item" %>
          <%= link_to '過去の課題図書', books_path , class:"navbar-item" %>
          <%= link_to "マイページ", user_path(current_user), class: "navbar-item" %> 
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: gold;"></i>
            <%= link_to "通知", notifications_path, class: "navbar-item has-background-warning has-text-dark"%>
          <% else %>
            <%= link_to "通知", notifications_path, class: "navbar-item"%>
          <% end %>
          

          <div class="navbar-item has-dropdown is-hoverable">
            <p class="navbar-link">
              その他
            </p>
            <div class="navbar-dropdown">
              <%= link_to '基本情報の編集', edit_user_registration_path ,class:"navbar-item"%>
              <a class="navbar-item">
                ご要望
              </a>
              <a class="navbar-item">
                お問い合わせ
              </a>
              <hr class="navbar-divider">
              <a class="navbar-item">
                Report an issue
              </a>
            </div>
          </div>
          <div class="navbar-item">
            <%= link_to 'ログアウト',destroy_user_session_path, method: :delete, class:"button is-danger" %>
          </div>
        </div>
      </div>
    <% else %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end">
          <%= link_to '今週の課題図書', root_url , class:"navbar-item" %>
          <%= link_to '過去の課題図書', books_path , class:"navbar-item" %>
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "ログイン", new_user_session_path, class: "button is-primary navbar-item" %>
              </p>
              <p class="control">
                <%= link_to "新規登録", new_user_registration_path, class: "button is-danger navbar-item" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </nav>

  <%= yield %>

    <script type="text/javascript">
      document.querySelector('.navbar-burger').addEventListener("click", toggleNav);

      function toggleNav() {
              var nav = document.querySelector('.navbar-menu');
              if(nav.className == "navbar-menu") {
                  nav.className = "navbar-menu is-active";
              } else {
                  nav.className = "navbar-menu";
              }
      }
    </script>

  </body>
</html>